%已知下一次碰撞需要的时间是Tremain. 序号是NextCollision.
%更新所有球的P,V和v.
P=P+V*Tremain;
[V(P(NextCollision(1))),V(P(NextCollision(1)))]=.....
    collision(V(NextCollision(1)),V(NextCollision(2))......
             ,P(NextCollision(1))-P(NextCollision(2)));